import Head from 'next/head'
import Register from '../component/Register'
import Login from '../component/Login'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'


export default function Home() {

    const [form, useForm] = useState(0);

    function FormRender(){
      if(form ==0){
        return <Register/>
      }
      else if(form ==1){
        return <Login/>
      }
    }

  return (
    <div className='h-screen bg-gradient-to-l from-yellow-300 to-red-500' >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <button onClick={()=>{ useForm(form = 0) }} className='p-3 m-3 px-5 bg-yellow-400 border-solid border-2 border-light-blue-500 hover:border-double border-4 border-light-blue-500' >Register</button>
    <button onClick={()=>{ useForm(form = 1) }} className='p-3 m-3 px-5 bg-yellow-400 border-solid border-2 border-light-blue-500 hover:border-double border-4 border-light-blue-500' >Login</button>
    <FormRender/>
    {
    console.log(form)
    }

    
      
    </div>
  )
}
